use std::collections::HashMap;
use std::fmt;

use crate::error::CargoArxmlError;
use crate::parser::ir::ArxmlProject;

pub mod proxy;
pub mod skeleton;
pub mod tests_gen;
pub mod traits;
pub mod types;

/// Describes an ID that was auto-assigned because the ARXML did not provide one.
#[derive(Debug, Clone)]
pub struct IdAssignment {
    pub service_name: String,
    pub element_name: Option<String>,
    pub kind: IdKind,
    pub assigned_value: u16,
}

#[derive(Debug, Clone)]
pub enum IdKind {
    ServiceId,
    MethodId,
    EventId,
    EventGroupId,
}

impl fmt::Display for IdAssignment {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match (&self.kind, &self.element_name) {
            (IdKind::ServiceId, _) => write!(
                f,
                "service '{}': missing service ID, auto-assigned {:#06x}",
                self.service_name, self.assigned_value
            ),
            (IdKind::MethodId, Some(name)) => write!(
                f,
                "service '{}', method '{}': missing method ID, auto-assigned {:#06x}",
                self.service_name, name, self.assigned_value
            ),
            (IdKind::EventId, Some(name)) => write!(
                f,
                "service '{}', event '{}': missing event ID, auto-assigned {:#06x}",
                self.service_name, name, self.assigned_value
            ),
            (IdKind::EventGroupId, Some(name)) => write!(
                f,
                "service '{}', event '{}': missing event group ID, auto-assigned {:#06x}",
                self.service_name, name, self.assigned_value
            ),
            _ => write!(
                f,
                "service '{}': missing {:?} ID, auto-assigned {:#06x}",
                self.service_name, self.kind, self.assigned_value
            ),
        }
    }
}

/// Top-level code generator.
///
/// Takes an [`ArxmlProject`] IR and produces a map of
/// `filename → Rust source code`.  Each value is a fully-formatted Rust
/// source file ready to be written to disk.
pub struct CodeGenerator<'a> {
    project: &'a ArxmlProject,
}

impl<'a> CodeGenerator<'a> {
    pub fn new(project: &'a ArxmlProject) -> Self {
        Self { project }
    }

    /// Generate all Rust source files for the project.
    ///
    /// Returns a tuple of `(files, auto_assignments)`. Files is a map of
    /// `filename → source`. Auto-assignments lists every ID that was
    /// invented because the ARXML lacked a SOME/IP deployment for it.
    ///
    /// Callers should inspect `auto_assignments` and decide whether to
    /// warn, error, or proceed silently.
    pub fn generate(
        &self,
    ) -> Result<(HashMap<String, String>, Vec<IdAssignment>), CargoArxmlError> {
        let mut project = self.project.clone();
        let auto_assignments = assign_default_ids(&mut project);

        let mut output: HashMap<String, String> = HashMap::new();

        // Data type definitions
        let types_src = types::generate_types(&project)?;
        output.insert("types.rs".to_string(), types_src);

        // Service traits
        let traits_src = traits::generate_traits(&project)?;
        output.insert("traits.rs".to_string(), traits_src);

        // Per-service proxy and skeleton stubs
        for svc in &project.services {
            let proxy_src = proxy::generate_proxy(svc, &project)?;
            let proxy_file = format!("proxy/{}.rs", snake_case(&svc.short_name));
            output.insert(proxy_file, proxy_src);

            let skeleton_src = skeleton::generate_skeleton(svc, &project)?;
            let skeleton_file = format!("skeleton/{}.rs", snake_case(&svc.short_name));
            output.insert(skeleton_file, skeleton_src);
        }

        // Test scaffolding
        let tests_src = tests_gen::generate_tests(&project)?;
        output.insert("tests.rs".to_string(), tests_src);

        // mod.rs entry point
        let mod_src = generate_mod_rs(&project);
        output.insert("mod.rs".to_string(), mod_src);

        Ok((output, auto_assignments))
    }
}

/// Generate a `mod.rs` that re-exports all generated modules.
fn generate_mod_rs(project: &ArxmlProject) -> String {
    let mut lines = vec![
        "//! Auto-generated by cargo-arxml. Do not edit.".to_string(),
        String::new(),
        "#[allow(unused_variables, unused_mut)]".to_string(),
        "pub mod types;".to_string(),
        "#[allow(unused_variables, unused_mut)]".to_string(),
        "pub mod traits;".to_string(),
    ];

    // Collect service module names
    let svc_mods: Vec<String> = project
        .services
        .iter()
        .map(|s| snake_case(&s.short_name))
        .collect();

    if !svc_mods.is_empty() {
        lines.push(String::new());
        lines.push("#[allow(unused_variables, unused_mut)]".to_string());
        lines.push("pub mod proxy {".to_string());
        for m in &svc_mods {
            lines.push(format!("    pub mod {m};"));
        }
        lines.push("}".to_string());

        lines.push(String::new());
        lines.push("#[allow(unused_variables, unused_mut)]".to_string());
        lines.push("pub mod skeleton {".to_string());
        for m in &svc_mods {
            lines.push(format!("    pub mod {m};"));
        }
        lines.push("}".to_string());
    }

    lines.push(String::new());
    lines.join("\n")
}

/// Assign default SOME/IP IDs to services, methods, and events that don't have them.
///
/// Returns a list of every ID that was auto-assigned. An empty list means all
/// IDs were already present in the ARXML (the ideal case).
///
/// Auto-assigned IDs avoid collisions with explicit IDs already present in the
/// same service by collecting used IDs first and picking the next available value.
pub fn assign_default_ids(project: &mut ArxmlProject) -> Vec<IdAssignment> {
    use std::collections::HashSet;

    let mut assignments = Vec::new();

    // Collect existing service IDs to avoid collisions at workspace level.
    let mut used_service_ids: HashSet<u16> = project
        .services
        .iter()
        .filter_map(|s| s.service_id)
        .collect();

    for svc in project.services.iter_mut() {
        if svc.service_id.is_none() {
            let id = next_available(0x1000, &used_service_ids);
            used_service_ids.insert(id);
            svc.service_id = Some(id);
            assignments.push(IdAssignment {
                service_name: svc.short_name.clone(),
                element_name: None,
                kind: IdKind::ServiceId,
                assigned_value: id,
            });
        }

        // Collect existing method IDs within this service.
        let mut used_method_ids: HashSet<u16> = svc
            .methods
            .iter()
            .filter_map(|m| m.method_id)
            .collect();

        for method in svc.methods.iter_mut() {
            if method.method_id.is_none() {
                let id = next_available(0x0001, &used_method_ids);
                used_method_ids.insert(id);
                method.method_id = Some(id);
                assignments.push(IdAssignment {
                    service_name: svc.short_name.clone(),
                    element_name: Some(method.name.clone()),
                    kind: IdKind::MethodId,
                    assigned_value: id,
                });
            }
        }

        // Collect existing event IDs within this service.
        let mut used_event_ids: HashSet<u16> = svc
            .events
            .iter()
            .filter_map(|e| e.event_id)
            .collect();
        let mut used_event_group_ids: HashSet<u16> = svc
            .events
            .iter()
            .filter_map(|e| e.event_group_id)
            .collect();

        for event in svc.events.iter_mut() {
            if event.event_id.is_none() {
                let id = next_available(0x8001, &used_event_ids);
                used_event_ids.insert(id);
                event.event_id = Some(id);
                assignments.push(IdAssignment {
                    service_name: svc.short_name.clone(),
                    element_name: Some(event.name.clone()),
                    kind: IdKind::EventId,
                    assigned_value: id,
                });
            }
            if event.event_group_id.is_none() {
                let id = next_available(0x0001, &used_event_group_ids);
                used_event_group_ids.insert(id);
                event.event_group_id = Some(id);
                assignments.push(IdAssignment {
                    service_name: svc.short_name.clone(),
                    element_name: Some(event.name.clone()),
                    kind: IdKind::EventGroupId,
                    assigned_value: id,
                });
            }
        }
    }

    assignments
}

/// Find the next available ID starting from `start` that is not in `used`.
fn next_available(start: u16, used: &std::collections::HashSet<u16>) -> u16 {
    let mut id = start;
    while used.contains(&id) {
        id = id.checked_add(1).expect("SOME/IP ID space exhausted");
    }
    id
}

// ---------------------------------------------------------------------------
// Helpers shared across submodules
// ---------------------------------------------------------------------------

/// Convert a PascalCase / camelCase name to snake_case.
pub(crate) fn snake_case(name: &str) -> String {
    let mut out = String::with_capacity(name.len() + 4);
    for (i, ch) in name.chars().enumerate() {
        if ch.is_uppercase() && i > 0 {
            out.push('_');
        }
        out.extend(ch.to_lowercase());
    }
    out
}
