use std::collections::HashMap;

use crate::error::CargoArxmlError;
use crate::parser::ir::ArxmlProject;

pub mod proxy;
pub mod skeleton;
pub mod tests_gen;
pub mod traits;
pub mod types;

/// Top-level code generator.
///
/// Takes an [`ArxmlProject`] IR and produces a map of
/// `filename → Rust source code`.  Each value is a fully-formatted Rust
/// source file ready to be written to disk.
pub struct CodeGenerator<'a> {
    project: &'a ArxmlProject,
}

impl<'a> CodeGenerator<'a> {
    pub fn new(project: &'a ArxmlProject) -> Self {
        Self { project }
    }

    /// Generate all Rust source files for the project.
    ///
    /// Returns a `HashMap<filename, source>`.  Filenames are relative paths
    /// (e.g. `"types.rs"`, `"proxy/battery_service.rs"`).
    pub fn generate(&self) -> Result<HashMap<String, String>, CargoArxmlError> {
        let mut project = self.project.clone();
        assign_default_ids(&mut project);

        let mut output: HashMap<String, String> = HashMap::new();

        // Data type definitions
        let types_src = types::generate_types(&project)?;
        output.insert("types.rs".to_string(), types_src);

        // Service traits
        let traits_src = traits::generate_traits(&project)?;
        output.insert("traits.rs".to_string(), traits_src);

        // Per-service proxy and skeleton stubs
        for svc in &project.services {
            let proxy_src = proxy::generate_proxy(svc, &project)?;
            let proxy_file = format!("proxy/{}.rs", snake_case(&svc.short_name));
            output.insert(proxy_file, proxy_src);

            let skeleton_src = skeleton::generate_skeleton(svc, &project)?;
            let skeleton_file = format!("skeleton/{}.rs", snake_case(&svc.short_name));
            output.insert(skeleton_file, skeleton_src);
        }

        // Test scaffolding
        let tests_src = tests_gen::generate_tests(&project)?;
        output.insert("tests.rs".to_string(), tests_src);

        // mod.rs entry point
        let mod_src = generate_mod_rs(&project);
        output.insert("mod.rs".to_string(), mod_src);

        Ok(output)
    }
}

/// Generate a `mod.rs` that re-exports all generated modules.
fn generate_mod_rs(project: &ArxmlProject) -> String {
    let mut lines = vec![
        "//! Auto-generated by cargo-arxml. Do not edit.".to_string(),
        String::new(),
        "#[allow(unused_variables, unused_mut)]".to_string(),
        "pub mod types;".to_string(),
        "#[allow(unused_variables, unused_mut)]".to_string(),
        "pub mod traits;".to_string(),
    ];

    // Collect service module names
    let svc_mods: Vec<String> = project
        .services
        .iter()
        .map(|s| snake_case(&s.short_name))
        .collect();

    if !svc_mods.is_empty() {
        lines.push(String::new());
        lines.push("#[allow(unused_variables, unused_mut)]".to_string());
        lines.push("pub mod proxy {".to_string());
        for m in &svc_mods {
            lines.push(format!("    pub mod {m};"));
        }
        lines.push("}".to_string());

        lines.push(String::new());
        lines.push("#[allow(unused_variables, unused_mut)]".to_string());
        lines.push("pub mod skeleton {".to_string());
        for m in &svc_mods {
            lines.push(format!("    pub mod {m};"));
        }
        lines.push("}".to_string());
    }

    lines.push(String::new());
    lines.join("\n")
}

/// Assign default SOME/IP IDs to services, methods, and events that don't have them.
/// Uses sequential assignment: service IDs start at 0x1000, method IDs at 0x0001,
/// event IDs at 0x8001 (events use the 0x8000+ range per SOME/IP spec).
pub fn assign_default_ids(project: &mut ArxmlProject) {
    for (svc_idx, svc) in project.services.iter_mut().enumerate() {
        if svc.service_id.is_none() {
            svc.service_id = Some(0x1000 + svc_idx as u16);
        }
        for (m_idx, method) in svc.methods.iter_mut().enumerate() {
            if method.method_id.is_none() {
                method.method_id = Some(1 + m_idx as u16);
            }
        }
        for (e_idx, event) in svc.events.iter_mut().enumerate() {
            if event.event_id.is_none() {
                event.event_id = Some(0x8001 + e_idx as u16);
            }
            if event.event_group_id.is_none() {
                event.event_group_id = Some(1 + e_idx as u16);
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Helpers shared across submodules
// ---------------------------------------------------------------------------

/// Convert a PascalCase / camelCase name to snake_case.
pub(crate) fn snake_case(name: &str) -> String {
    let mut out = String::with_capacity(name.len() + 4);
    for (i, ch) in name.chars().enumerate() {
        if ch.is_uppercase() && i > 0 {
            out.push('_');
        }
        out.extend(ch.to_lowercase());
    }
    out
}
